"""transaction model

Revision ID: 1b4be1363a42
Revises: 1c9688be16cc
Create Date: 2024-02-13 18:53:41.619857

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b4be1363a42"
down_revision: Union[str, None] = "1c9688be16cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("currency", sa.VARCHAR(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transaction_amount_btree",
        "transaction",
        ["amount"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_transaction_currency_btree",
        "transaction",
        ["currency"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_transaction_date_btree",
        "transaction",
        ["date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_transaction_note_btree",
        "transaction",
        ["note"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transaction_note_btree", table_name="transaction", postgresql_using="btree"
    )
    op.drop_index(
        "ix_transaction_date_btree", table_name="transaction", postgresql_using="btree"
    )
    op.drop_index(
        "ix_transaction_currency_btree",
        table_name="transaction",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_transaction_amount_btree",
        table_name="transaction",
        postgresql_using="btree",
    )
    op.drop_table("transaction")
    # ### end Alembic commands ###
