"""Initial

Revision ID: 3a46031b9c77
Revises: 
Create Date: 2024-02-12 13:00:47.231506

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3a46031b9c77"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
