"""user settings model

Revision ID: 3adce4f7a117
Revises: ac7e6416c36f
Create Date: 2024-02-13 18:00:34.679342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3adce4f7a117"
down_revision: Union[str, None] = "ac7e6416c36f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("notification_on", sa.Boolean(), nullable=False),
        sa.Column("default_currency", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_settings_default_currency_btree",
        "user_settings",
        ["default_currency"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_user_settings_notification_on_btree",
        "user_settings",
        ["notification_on"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_settings_notification_on_btree",
        table_name="user_settings",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_user_settings_default_currency_btree",
        table_name="user_settings",
        postgresql_using="btree",
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###
