"""device model

Revision ID: 615e7cb6d88a
Revises: 3adce4f7a117
Create Date: 2024-02-13 18:01:23.348560

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "615e7cb6d88a"
down_revision: Union[str, None] = "3adce4f7a117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "last_login", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("fcm_token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_device_last_login_btree",
        "device",
        ["last_login"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_device_user_id_btree",
        "device",
        ["user_id"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_device_user_id_btree", table_name="device", postgresql_using="btree"
    )
    op.drop_index(
        "ix_device_last_login_btree", table_name="device", postgresql_using="btree"
    )
    op.drop_table("device")
    # ### end Alembic commands ###
