"""user model

Revision ID: ac7e6416c36f
Revises: 3a46031b9c77
Create Date: 2024-02-13 16:50:52.551421

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac7e6416c36f"
down_revision: Union[str, None] = "3a46031b9c77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "ix_user_birthday_btree",
        "user",
        ["birthday"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_user_email_btree", "user", ["email"], unique=True, postgresql_using="btree"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email_btree", table_name="user", postgresql_using="btree")
    op.drop_index("ix_user_birthday_btree", table_name="user", postgresql_using="btree")
    op.drop_table("user")
    # ### end Alembic commands ###
